services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - 80

      
  webapp:
    build: ./backend
    container_name: backend
    expose:
      - 8080
    environment:
      JWT_SECRET_KEY: your_secret_key
#   volumes:
#     - ${USERPROFILE}\.aspnet\https:C:\https:ro

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ctfdb
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx-proxy:
     image: nginx:alpine
     container_name: proxy
     ports:
       - "80:80"
     volumes:
       - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - frontend
     # - backend

volumes:
  db-data:
